In [1]:
import threading
from queue import Queue
import time

In [2]:
import gym

In [3]:
env=gym.make('MsPacman-v0')

In [4]:
env.action_space

Discrete(9)

In [5]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[228 111 111]
  [228 111 111]
  [228 111 111]
  ...
  [228 111 111]
  [228 111 111]
  [228 111 111]]

 [[228 111 111]
  [228 111 111]
  [228 111 111]
  ...
  [228 111 111]
  [228 111 111]
  [228 111 111]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[228 111 111]
  [228 111 111]
  [228 111 111]
  ...
  [228 111 111]
  [228 111 111]
  [228 111 111]]

 [[228 111 111]
  [228 111 111]
  [228 111 111]
  ...
  [228 111 111]
  [228 111 111]
  [228 111 111]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..

In [15]:
for i in range(100):
    obs=env.reset()
    env.render()
    action=env.action_space.sample()

In [16]:
env.close()

In [17]:
frames=[]
total_reward=[]
max_iter=2000
change_steps=10
env.reset()
for i in range(max_iter):
    img=env.render(mode='rgb_array')
    frames.append(img)
    if i%change_steps==0:
        action=env.action_space.sample()
    obs,reward, done,info=env.step(action)
    total_reward.append(reward)
    if done:
        break
env.close()

In [22]:
frames=np.array(frames)

In [29]:
from keras.models import Sequential
from keras.layers import Dense, Dropout,Flatten
model=Sequential()
model.add(Dense(15,activation='elu',input_shape=(210, 160, 3)))
model.add(Dense(10,activation='elu'))
model.add(Flatten())
model.add(Dense(1,activation='elu'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 210, 160, 15)      60        
_________________________________________________________________
dense_14 (Dense)             (None, 210, 160, 10)      160       
_________________________________________________________________
flatten_5 (Flatten)          (None, 336000)            0         
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 336001    
Total params: 336,221
Trainable params: 336,221
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')

In [65]:
np.array(total_reward).shape

(200,)

In [51]:
frames=np.array(frames).reshape(200,210,160,3)

In [49]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler((0,0.99))

In [50]:
total_reward=scaler.fit_transform(pd.DataFrame(total_reward)).flatten()

In [55]:
history=model.fit(frames,total_reward,batch_size=1)

Epoch 1/1
716/716 [==============================] - 9s 13ms/step - loss: 0.0000e+00
